### ISSUE TITLE
Tiled layers in desktop mode

### ISSUE THREAD

**Issue by Xenophon382** [uprel/gisapp#111]
Hello,
i just want to know if there is any way to get this app working with tiled layers on desktop mode 
 ( i saw is available for mobile )

**Comment by uprel** [comment]
So you want that main QGIS layer is tiled instead of single image?

It's correct that current setting only applies to mobile client, for web client you have to set this line to false:
https://github.com/uprel/gisapp/blob/4c066f6f531c436f804e420a356a379b2d95b785/client/site/js/LoadAppProjectData.js#L411

Then you must have debug variable set to TRUE in Admin/settings.php and trigger version in  version.txt to any different number then current to mark browser to reload javascript files and not use cached version
