### ISSUE TITLE
Print PDF with Base Layers

### ISSUE THREAD

**Issue by uprel** [uprel/gisapp#12]
This is a major issue, because GetPrint request to QGIS Server is just for QGIS project and does not include any base layers that we have included in client. Idea how to solve this:
- add selected base layer to GetPrint Request
- initially prepare QGIS project with all base layers that can be used in projects
- in QGIS proxy catch GetPrint request and replace project with on the fly generated project from 
  original project, merged with base layers and appropriate base layer selected
- if on the fly solution won't work then prepare script to generate such print projects on disk.

**Comment by sasoloce** [comment]
Hi,

first, thanks and congratulations for this incredible project. I am using it and to be honest I am very surprised with the results. However, I am a bit stopped with plotting, since it does not allow plotting the base layers and also gives problems with some configurations of the designs, such as when you use legends or texts. Any advice or news about it? Thanks in advance.

**Comment by uprel** [comment]
Hi, thanks. I know this is important feature but can't dedicate enough time and resource to fix this. Couple of possible solutions any help and support welcomed. Other advice is to use QGIS 2.14.x and not 2.18 due to some bugs with GetPrint.

**Comment by uprel** [comment]
I added this feature to next planned release 1.6. Probably till end of this month.

**Comment by sasoloce** [comment]
Hi,

 

Thank very much!!!

 

I´m working a bit over the interface. First, I added a new feature that allow us to define different coordinate systems for viewing. That is important because if you are using Google, Bing, etc as baselayer you need to select EPSG:3857 , so you can´t use your official coordinate systems. To allow that,  we define a “main” and a “visual” projections. Main is used for all the layers to be compatible with base layers and visual to show coordinates in the interface:

 



 

If you are interested on this I can send you the eqwc.js file. Maybe this configuration should be out of eqwc.js but now and using it.

 

Thanks again for you incredible tool!

 

 

De: Uros Preloznik [mailto:notifications@github.com] 
Enviado el: domingo, 5 de noviembre de 2017 13:17
Para: uprel/gisapp
CC: sasoloce; Comment
Asunto: Re: [uprel/gisapp] Print PDF with Base Layers (#12)

 

I added this feature to next planned release 1.6. Probably till end of this month.

**Comment by uprel** [comment]
Just a hint if you decided to do some customizations in the code. First enable debug mode /admin/settings.php so that client will load source files and not eqwc.js. Then you can examine and edit source javascript files and if you come up with something usefull, great, share it via pull request to test.

**Comment by sasoloce** [comment]
Ok, understood.

 

I will do and send.

 

De: Uros Preloznik [mailto:notifications@github.com] 
Enviado el: lunes, 6 de noviembre de 2017 12:39
Para: uprel/gisapp
CC: sasoloce; Comment
Asunto: Re: [uprel/gisapp] Print PDF with Base Layers (#12)

 

Just a hint if you decided to do some customizations in the code. First enable debug mode /admin/settings.php so that client will load source files and not eqwc.js. Then you can examine and edit source javascript files and if you come up with something usefull, great, share it via pull request to test.

**Comment by sasoloce** [comment]
Hi,

 

I´ve used debug mode to test it without problems. But I think this change, if you are interested on it, must be configured in other way in future release (maybe in other config_view_proj.js or something like that). I send you the GUI.js, with the changes, localized since 400 row and in row 342 (

                                                                              bbar: creaBottomBar() that calls my function).

 

 

In WebgisInit_functions.js, you must change the way to return coordinates, in order to apply the the appropiate transformation:

 

geoExtMap.map.events.register("mousemove", this, function(a) {

                                               

                                               var position = geoExtMap.map.getLonLatFromPixel(a.xy).transform(new OpenLayers.Projection(proj_main),  epsgText.getValue()); 

                                               //console.log(position);

            //lonText.setText(position.lon.toFixed(3));

            //latText.setText(position.lat.toFixed(3));

                                                               

                                               //a = geoExtMap.map.events.getMousePosition(a);

            //a = geoExtMap.map.getLonLatFromPixel(a);

            coordinateTextField.setRawValue(position.lon.toFixed(3) + "," + position.lat.toFixed(3))

        });

 

Sorry for this little mess. Rename the files to js.

 

Regards, 

Santigo Soto.

 

 

De: Uros Preloznik [mailto:notifications@github.com] 
Enviado el: lunes, 6 de noviembre de 2017 12:39
Para: uprel/gisapp
CC: sasoloce; Comment
Asunto: Re: [uprel/gisapp] Print PDF with Base Layers (#12)

 

Just a hint if you decided to do some customizations in the code. First enable debug mode /admin/settings.php so that client will load source files and not eqwc.js. Then you can examine and edit source javascript files and if you come up with something usefull, great, share it via pull request to test.

**Comment by uprel** [comment]
Anyone welcome to contribute but over pull requests please.

**Comment by uprel** [comment]
This is possible with release 1.6. [Documentation](https://github.com/uprel/gisapp/wiki/5.5.-Print#base-layers)
