### ISSUE TITLE
attribute table rows

### ISSUE THREAD

**Issue by Prajith76** [uprel/gisapp#51]
I cannot see the attribute table completely when adding a postgis layer with over 3900 rows, the layer is displayed properly over the map but the attribute table shows only 2000 records. Is there any limit of rows that can be displayed? Is this a known issue?

**Comment by uprel** [comment]
WMS map layer and its attributes have no real connection in client. Attributes are loaded with GetFeatureInfo request with empty filter and of course you must set some limit. This is set in Customizations.js https://github.com/uprel/gisapp/blob/97afa7b0c9a0effb629c7918fbbf38271d331f62/client/site/js/Customizations.js#L27

I will provide a setting to easily adjust that, because of this- https://github.com/uprel/gisapp/wiki/4.-Running-client#changing-code-or-debugging

**Comment by Prajith76** [comment]
Thank you very much for the swift response. I have changed the gridResults to 3000 but unfortunately no changes in the feature count in the attribute table. Still it shows 2000 only. Is there is any other settings I need to change?

**Comment by uprel** [comment]
You modified one of source files, Client by default loads minified single javascript file (eqwc.js). To use source files you have to enable debug mode. Explained in url above. So that is reason to move this into client side settings.js

**Comment by uprel** [comment]
Sorry, correct line for setting for layer attribute table is this
https://github.com/uprel/gisapp/blob/97afa7b0c9a0effb629c7918fbbf38271d331f62/client/site/js/LayerActions.js#L347

The first one is for table initially displayed on client start. I will fix that both of this numbers will use new single setting

**Comment by Prajith76** [comment]
It is working and now I am able to set the limits. Thank you very much for your help and support, much appreciated.
