### ISSUE TITLE
Set max. zoom scale

### ISSUE THREAD

**Issue by miszokienka** [uprel/gisapp#77]
I want to allow zooming max up to 1:1000 because if you zoom more than 1:1000 than Google Maps background is "floating". By floating I mean that it's moving separately from layers of my gisapp project.

**Comment by uprel** [comment]
Google layer has different transition effect then other layers. There is a setting here, 
https://github.com/uprel/gisapp/blob/2ad0a7898a10ceba7b9c2f2352f7bf742b41a88d/client/site/js/LoadAppProjectData.js#L284

try adjusting it to value 10 and try again (in debug mode). I think this is what you mean, at the end layers are matched just transition is different or maybe floating.

By default Google Maps has 20 zoom levels (max 1:1128), to have more levels change value in database.

**Comment by uprel** [comment]
Is this solution OK, or is there any other problem?

**Comment by miszokienka** [comment]
It's better but it has still not fixed the problem.
The problem is that if I zoom more than 1:1128 than Google Maps and my project layers are floating. It doesn't happen until the scale is up to 1:1128.
I know that Google is not present with bigger zoom level and that's why I'm thinking about providing a setting that will dismiss zooming more than 1:1128. Do you think it is possible?

**Comment by miszokienka** [comment]
I think providing _maxScale_ and _minScale_ (as in  #80) will be the right solution to solve my problem.

**Comment by uprel** [comment]
I provided solution for #80. It's not possible to get it at the time of loading the layer, so needs to be set explicitly. For your case I do not understand completely issue. Because if you load Google Maps you cannot zoom over 1:1128 unless you specify more zoom levels for Google layer (if they exists at first place)

**Comment by uprel** [comment]
#80 is now closed. I don't think it's related. Can you provide more info or link to test this issue, if it still exists

**Comment by uprel** [comment]
I played with this a little and I think I saw what happened. You increased zoom levels for Google layer and you probably zoomed over 1128 in area where this is not supported and then this weird effect occured. Because Google layer did not zoom and QGIS layer did and then they are floating like you wrote. I tried on different areas and in some countries are fine zooming to 282 (level 22) and in some not. So I don't really see issue here, if this happens just lower zoom level in database for that Google layer.
